d3.select("body").append("p").text("Hello").style("color","blue")
d3.select("body").append("p").text("My")
d3.select("body").append("p").text("Name")
d3.select("body").append("p").text("IS")
d3.select("body").append("p").text("Caitlyn")